name: LFFPlugin
main: LFFPlugin\Main
version: 1.0.0
api: [5.0.0]
author: Froz
description: Un plugin que abre un menú GUI con el comando /lff.
commands:
  lff:
    description: Abre el menú Looking for Faction.
    usage: /lff
    permission: lffplugin.command.lff
permissions:
  lffplugin.command.lff:
    description: Permite usar el comando /lff
    default: true
